{"name": "test_successful_login", "status": "failed", "statusDetails": {"message": "AssertionError: assert 404 == 200\n +  where 404 = <Response [404]>.status_code", "trace": "config = {'allure': {'build_name': 'Local Test Run', 'build_order': '1', 'executor_name': 'Local Machine', 'report_name': 'API ...tps://jsonplaceholder.typicode.com/', 'local_flask': 'http://127.0.0.1:5000/api', 'reqres': 'https://reqres.in/'}, ...}\n\n    @allure.feature(\"Authentication\")\n    @allure.story(\"Successful login\")\n    def test_successful_login(config):\n        client = AuthClient(config[\"api_base_url\"])\n        response = client.login(\"eve.holt@reqres.in\", \"cityslicka\")\n    \n        with allure.step(\"Verify successful login\"):\n>           assert response.status_code == 200\nE           assert 404 == 200\nE            +  where 404 = <Response [404]>.status_code\n\ntests\\test_auth_api.py:12: AssertionError"}, "steps": [{"name": "Verify successful login", "status": "failed", "statusDetails": {"message": "AssertionError: assert 404 == 200\n +  where 404 = <Response [404]>.status_code\n", "trace": "  File \"C:\\Users\\n.krotsik\\Desktop\\Pytest\\automation_project_API\\tests\\test_auth_api.py\", line 12, in test_successful_login\n    assert response.status_code == 200\n"}, "start": 1747040363958, "stop": 1747040363958}], "start": 1747040363792, "stop": 1747040363959, "uuid": "38d67ae9-6f95-4164-9f7c-7d348d2c742c", "historyId": "4893e92e518e23e3b7de348fd5509cd4", "testCaseId": "4893e92e518e23e3b7de348fd5509cd4", "fullName": "tests.test_auth_api#test_successful_login", "labels": [{"name": "story", "value": "Successful login"}, {"name": "feature", "value": "Authentication"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_auth_api"}, {"name": "host", "value": "PLWRS-PF43AQAR"}, {"name": "thread", "value": "10160-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_auth_api"}]}