{"name": "test_get_nonexistent_user[9999]", "status": "broken", "statusDetails": {"message": "KeyError: 'api_base_url'", "trace": "config = {'allure': {'build_name': 'Local Test Run', 'build_order': '1', 'executor_name': 'Local Machine', 'report_name': 'API ...'}, 'default_headers': {'Accept': 'application/json', 'Content-Type': 'application/json'}, 'environment': 'Local', ...}\ninvalid_id = 9999\n\n    @allure.feature(\"Negative Test - GET /users/{invalid_id}\")\n    @pytest.mark.parametrize(\"invalid_id\", [0, 9999, \"abc\"])\n    def test_get_nonexistent_user(config, invalid_id):\n>       client = UserClient(config[\"api_base_url\"])\nE       KeyError: 'api_base_url'\n\ntests\\test_users_api.py:37: KeyError"}, "parameters": [{"name": "invalid_id", "value": "9999"}], "start": 1747038420667, "stop": 1747038420667, "uuid": "79120e56-6983-4931-babe-c11204058ac1", "historyId": "9dd4227a1a891731594d45b2a96bf0d7", "testCaseId": "7f0315b27c020144d2b188e9b279c636", "fullName": "tests.test_users_api#test_get_nonexistent_user", "labels": [{"name": "feature", "value": "Negative Test - GET /users/{invalid_id}"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_users_api"}, {"name": "host", "value": "PLWRS-PF43AQAR"}, {"name": "thread", "value": "17196-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_users_api"}]}