{"name": "test_get_nonexistent_user[0]", "status": "broken", "statusDetails": {"message": "KeyError: 'api_base_url'", "trace": "config = {'allure': {'build_name': 'Local Test Run', 'build_order': '1', 'executor_name': 'Local Machine', 'report_name': 'API ...'}, 'default_headers': {'Accept': 'application/json', 'Content-Type': 'application/json'}, 'environment': 'Local', ...}\ninvalid_id = 0\n\n    @allure.feature(\"Negative Test - GET /users/{invalid_id}\")\n    @pytest.mark.parametrize(\"invalid_id\", [0, 9999, \"abc\"])\n    def test_get_nonexistent_user(config, invalid_id):\n>       client = UserClient(config[\"api_base_url\"])\nE       KeyError: 'api_base_url'\n\ntests\\test_users_api.py:37: KeyError"}, "parameters": [{"name": "invalid_id", "value": "0"}], "start": 1747038420652, "stop": 1747038420652, "uuid": "b28b9ced-5f87-4b53-9f8e-f4ceb0630b44", "historyId": "17341d05bcd8d58d3f209e9365cb7ce8", "testCaseId": "7f0315b27c020144d2b188e9b279c636", "fullName": "tests.test_users_api#test_get_nonexistent_user", "labels": [{"name": "feature", "value": "Negative Test - GET /users/{invalid_id}"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_users_api"}, {"name": "host", "value": "PLWRS-PF43AQAR"}, {"name": "thread", "value": "17196-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_users_api"}]}